### ISSUE TITLE
Change namespaces

### ISSUE THREAD

**Issue by igrangel** [igrangel/RDF-Py-Examples#2]
Instead of having something like: `@prefix ns1: <http://dbpedia.org/ontology/> . ` we should provide a more readable namespace, e.g., `@prefix dbonto: <http://dbpedia.org/ontology/> . ` or something like [here](http://linkedwiki.com/searchExample.php?page=1&q=&tag%5B%5D=465)

**Comment by mmaltsev** [comment]
The following namespaces are renamed:
`ns1: <http://dbpedia.org/ontology/>` -  `dbont`
`ns2: <http://dbpedia.org/property/>` -  `dbprop`
`ns3: <http://www.w3.org/ns/prov#>`  - `nsprov`
`ns4: <http://purl.org/voc/vrank#>` - `vocvr`
`ns5: <http://purl.org/linguistics/gold/>`  -  `lingg`

Result can be seen [here](https://github.com/igrangel/RDF-Py-Examples/blob/dev/query_all_p3.py)
